sudo: required
dist: trusty

services:
  - postgresql
  - elasticsearch

matrix:
  include:
    - language: python
      python:
        - "3.5"
      before_install:
        - sudo apt-get -y install software-properties-common
        - sudo add-apt-repository -y ppa:mc3man/trusty-media
        - sudo apt-get update
        - sudo apt-get -y --allow-unauthenticated install ffmpeg
        - cp server/config.yaml.dist config.yaml
        - sed -i -e 's/^#database:$/database:\ postgres:\/\/szuru:dog@localhost:5432\/szuru_test/' config.yaml
        - sed -i -e 's/^#elasticsearch:/elasticsearch:/' config.yaml
        - sed -i -e 's/^#    host: localhost$/    host: localhost/' config.yaml
        - sed -i -e 's/^#    port: 9200$/    port: 9200/' config.yaml
        - sed -i -e 's/^#    index: szurubooru$/    index: szurubooru/' config.yaml
        - sudo -i -u postgres createuser szuru -D -R -S
        - sudo -i -u postgres createdb szuru_test
        - sudo -i -u postgres psql -c "ALTER USER szuru PASSWORD 'dog';"
      install:
        - cd server
        - pip install -r requirements.txt
      script:
        - alembic upgrade head
        - py.test
